import React, { useEffect, useState } from 'react';
import { CreditCard, Loader2 } from 'lucide-react';
import apiClient from '../../../apiClient';

export const InvoicePaymentWidget: React.FC = () => {
  const [invoices, setInvoices] = useState<any[]>([]); const [methods, setMethods] = useState<any[]>([]);
  const [invoiceId, setInvoiceId] = useState(''); const [methodId, setMethodId] = useState(''); const [payer, setPayer] = useState(''); const [reference, setReference] = useState(''); const [file, setFile] = useState<File | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { Promise.all([apiClient.commerce.getMyInvoices(), apiClient.commerce.getPaymentMethods()]).then(([i, m]) => { setInvoices(i); setMethods(m); setInvoiceId(i.find((x: any) => ['issued', 'awaiting_payment'].includes(x.status))?.id || ''); setMethodId(m[0]?.id || ''); }).catch(() => setMessage('Unable to load payment details.')); }, []);
  const invoice = invoices.find(i => i.id === invoiceId);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); if (!invoice || !file) { setMessage('Choose an invoice and receipt file.'); return; } setBusy(true); setMessage(''); try { const receipt_storage_path = await apiClient.commerce.uploadReceipt(file); await apiClient.commerce.submitInvoicePayment(invoice.id, { payment_method_id: methodId, payer_name: payer, amount_claimed: Number(invoice.amount_due), transfer_reference: reference, receipt_storage_path }); setMessage('Payment proof submitted. We will respond within 24 business hours.'); setFile(null); setReference(''); } catch (err: any) { setMessage(err.message || 'Payment submission failed.'); } finally { setBusy(false); } };
  if (!invoice) return null;
  return <div className="card" style={{ padding: '18px' }}><h3 style={{ display: 'flex', alignItems: 'center', gap: 8, fontWeight: 800 }}><CreditCard size={18} /> Payment required</h3><p style={{ color: 'var(--text-secondary)', fontSize: '.85rem' }}>Invoice {invoice.reference} · ₦{Number(invoice.amount_due).toLocaleString()}</p><form onSubmit={submit} style={{ display: 'grid', gap: 8, marginTop: 12 }}><select className="input-field" value={invoiceId} onChange={e => setInvoiceId(e.target.value)}>{invoices.filter(i => ['issued', 'awaiting_payment'].includes(i.status)).map(i => <option key={i.id} value={i.id}>{i.reference} — ₦{Number(i.amount_due).toLocaleString()}</option>)}</select><select className="input-field" value={methodId} onChange={e => setMethodId(e.target.value)}>{methods.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select><input className="input-field" required placeholder="Payer name" value={payer} onChange={e => setPayer(e.target.value)} /><input className="input-field" required placeholder="Transfer reference" value={reference} onChange={e => setReference(e.target.value)} /><input required type="file" accept="image/jpeg,image/png,application/pdf" onChange={e => setFile(e.target.files?.[0] || null)} /><button className="btn btn-primary" disabled={busy}>{busy ? <Loader2 size={15} className="animate-spin" /> : 'Submit payment proof'}</button></form>{message && <p style={{ marginTop: 8, fontSize: '.8rem', color: 'var(--text-secondary)' }}>{message}</p>}</div>;
};
